# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Plugin-DebugLeakChecker
version:      0.01
author: syushi matsumoto <matsumoto@alink.co.jp>
build_requires:
  Test::More: 0
  Template: 0
  Devel::Leak::Object: 0
  Sledge::Plugin::BeforeOutput: 0
license: perl
version_from: lib/Sledge/Plugin/DebugLeakChecker.pm
installdirs:  site
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17

